### PR TITLE
6: Translation Mechanism

### PR DESCRIPTION
**Pull request by jhculb**
Opening new pull request for work after the accidental merge this morning

### CODE REVIEW

**Comment by jhculb** [comment]
Note to self: review how github deals with PRs

**Comment by jhculb** [comment]
I have noticed that in the rml-star-mappings there are both rml and rr references (bnode-1.ttl line 14 and 35)

**Comment by jhculb** [comment]
Hi @dachafra @andimou,

I've just run into the following potential error, when adding multiple predicateObjectMaps. I am 


```  rr:predicateObjectMap [
    ns0:objectMap [ rr:constant <http://example/q> ] ;
    rr:predicate rdf:predicate
  ], [
    ns0:objectMap [ rr:template "http://example/{c5}" ] ;
    rr:predicate rdf:object
  ], [
    ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;
    rr:predicate ns0:subject
  ] .
```

I would like to check that this is equivalent to 

```

  rr:predicateObjectMap [
    ns0:objectMap [ rr:constant <http://example/q> ] ;
    rr:predicate rdf:predicate
  ] .
 rr:predicateObjectMap [
    ns0:objectMap [ rr:template "http://example/{c5}" ] ;
    rr:predicate rdf:object
  ] .
 rr:predicateObjectMap [
    ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;
    rr:predicate ns0:subject
  ] .
```

I'm currently reading up on this but if you are around a faster answer would be appreciated :)

**Comment by dachafra** [comment]
If you are asking if the notation `rr:predicateObjectMap` is needed, it's.
Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap

**Comment by jhculb** [comment]
> If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`

Thanks for the swift reply!

First point:
Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.

Second point:
ns0 is an automatically generated namespace identifier (from RDFlib), e.g.
@prefix ns1: <http://www.w3.org/ns/r2rml#> .

**Comment by dachafra** [comment]
> > If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`
> 
> Thanks for the swift reply!
> 
> First point: Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.

You can print the rules in N-Triples to see all without BN

> Second point: ns0 is an automatically generated namespace identifier (from RDFlib), e.g. @Prefix ns1: http://www.w3.org/ns/r2rml# .

I think you can manage them with Namespaces right?

**Comment by jhculb** [comment]
I think that apart from the issue mentioned earlier I am almost finished.

**Comment by jhculb** [comment]
> > > If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`
> > 
> > 
> > Thanks for the swift reply!
> > First point: Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.
> 
> You can print the rules in N-Triples to see all without BN
> 
> > Second point: ns0 is an automatically generated namespace identifier (from RDFlib), e.g. @Prefix ns1: http://www.w3.org/ns/r2rml# .
> 
> I think you can manage them with Namespaces right?

First point, outputting using rdflib serialize and ntriples does include BNodes

Second point, the two namespaces are equivalent, just with a different variable. I haven't seen anything in the documentation that allows me edit these directly, I can see what I can do but I think apart from the naming convention (ns0 for (e.g.) rr, ns1 for (e.g.) rml) the generated reified documents are the same as the manually reified documents. (And apart from the first point)

**Comment by jhculb** [comment]
> > > > If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`
> > > 
> > > 
> > > Thanks for the swift reply!
> > > First point: Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.
> > 
> > 
> > You can print the rules in N-Triples to see all without BN
> > > Second point: ns0 is an automatically generated namespace identifier (from RDFlib), e.g. @Prefix ns1: http://www.w3.org/ns/r2rml# .
> > 
> > 
> > I think you can manage them with Namespaces right?
> 
> First point, outputting using rdflib serialize and ntriples does include BNodes (see syntax-2.ttl in /generated-rml-reified)
> 
> Second point, the two namespaces are equivalent, just with a different variable. I haven't seen anything in the documentation that allows me edit these directly, I can see what I can do but I think apart from the naming convention (ns0 for (e.g.) rr, ns1 for (e.g.) rml) the generated reified documents are the same as the manually reified documents. (And apart from the first point)

Hi @dachafra, on the first point:
I believe that the following two statements are equivalent:

```
@prefix ns1: <http://www.w3.org/ns/r2rml#> .
@prefix ns2: <http://semweb.mmlab.be/ns/rml#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/secondTM> a ns2:TriplesMap ;
    ns2:predicateObjectMap [ ns2:objectMap [ ns1:reference rdf:Statement ] ;
            ns1:predicate ns2:type ] ;
    ns1:predicateObjectMap [ ns2:objectMap [ ns1:constant <http://example/q> ] ;
            ns1:predicate rdf:predicate ],
        [ ns2:objectMap [ ns1:template "http://example/{c5}" ] ;
            ns1:predicate rdf:object ] .
```
and
```
@prefix ns1: <http://www.w3.org/ns/r2rml#> .
@prefix ns2: <http://semweb.mmlab.be/ns/rml#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/secondTM> a ns2:TriplesMap ;
    ns2:predicateObjectMap [ ns2:objectMap [ ns1:reference rdf:Statement ] ;
            ns1:predicate ns2:type ] ;
    ns1:predicateObjectMap [ ns2:objectMap [ ns1:constant <http://example/q> ] ;
            ns1:predicate rdf:predicate ] ; 
    ns1:predicateObjectMap [ ns2:objectMap [ ns1:template "http://example/{c5}" ] ;
            ns1:predicate rdf:object ] .
```
As they both give the same output in https://www.easyrdf.org/converter
```
<http://example.org/secondTM> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://semweb.mmlab.be/ns/rml#TriplesMap> .
<http://example.org/secondTM> <http://semweb.mmlab.be/ns/rml#predicateObjectMap> _:genid1 .
<http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid3 .
<http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid5 .
_:genid2 <http://www.w3.org/ns/r2rml#reference> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement> .
_:genid1 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid2 .
_:genid1 <http://www.w3.org/ns/r2rml#predicate> <http://semweb.mmlab.be/ns/rml#type> .
_:genid4 <http://www.w3.org/ns/r2rml#constant> <http://example/q> .
_:genid3 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid4 .
_:genid3 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> .
_:genid6 <http://www.w3.org/ns/r2rml#template> "http://example/{c5}" .
_:genid5 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid6 .
_:genid5 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> .
```
and
```
<http://example.org/secondTM> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://semweb.mmlab.be/ns/rml#TriplesMap> .
<http://example.org/secondTM> <http://semweb.mmlab.be/ns/rml#predicateObjectMap> _:genid1 .
<http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid3 .
<http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid5 .
_:genid2 <http://www.w3.org/ns/r2rml#reference> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement> .
_:genid1 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid2 .
_:genid1 <http://www.w3.org/ns/r2rml#predicate> <http://semweb.mmlab.be/ns/rml#type> .
_:genid4 <http://www.w3.org/ns/r2rml#constant> <http://example/q> .
_:genid3 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid4 .
_:genid3 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> .
_:genid6 <http://www.w3.org/ns/r2rml#template> "http://example/{c5}" .
_:genid5 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid6 .
_:genid5 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> .
```

Therefore I submit that I shouldn't code anything more as the output reification in both cases is equivalent.

**Comment by jhculb** [comment]
Current work left to do prior to review

- [ ] Check the namespaces aren't an issue with @dachafra 
- [ ] Check the reification is suitable with @dachafra 
- [ ] Fix datatype statements which should be references turning into template statements

**Comment by jhculb** [comment]
Hey @dachafra @andimou, 

Can I check whether I am correct in thinking line 50 in rml-star-mappings should be a rr:reference rather than a rml:reference?
Otherwise this is inconsistent with the bnode datatype references in rml-star-mappings.

**Comment by jhculb** [comment]
Hi @dachafra, @andimou.

I believe if my arguments above are convincing that I have completed the coding challenge.

**Comment by dachafra** [comment]
> Can I check whether I am correct in thinking line 50 in rml-star-mappings should be a rr:reference rather than a rml:reference?
> Otherwise this is inconsistent with the bnode datatype references in rml-star-mappings.

It is always rml:reference, rr:reference does not existe

**Comment by dachafra** [comment]
> > > > > If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`
> > > > 
> > > > 
> > > > Thanks for the swift reply!
> > > > First point: Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.
> > > 
> > > 
> > > You can print the rules in N-Triples to see all without BN
> > > > Second point: ns0 is an automatically generated namespace identifier (from RDFlib), e.g. @Prefix ns1: http://www.w3.org/ns/r2rml# .
> > > 
> > > 
> > > I think you can manage them with Namespaces right?
> > 
> > 
> > First point, outputting using rdflib serialize and ntriples does include BNodes (see syntax-2.ttl in /generated-rml-reified)
> > Second point, the two namespaces are equivalent, just with a different variable. I haven't seen anything in the documentation that allows me edit these directly, I can see what I can do but I think apart from the naming convention (ns0 for (e.g.) rr, ns1 for (e.g.) rml) the generated reified documents are the same as the manually reified documents. (And apart from the first point)
> 
> Hi @dachafra, on the first point: I believe that the following two statements are equivalent:
> 
> ```
> @prefix ns1: <http://www.w3.org/ns/r2rml#> .
> @prefix ns2: <http://semweb.mmlab.be/ns/rml#> .
> @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
> 
> <http://example.org/secondTM> a ns2:TriplesMap ;
>     ns2:predicateObjectMap [ ns2:objectMap [ ns1:reference rdf:Statement ] ;
>             ns1:predicate ns2:type ] ;
>     ns1:predicateObjectMap [ ns2:objectMap [ ns1:constant <http://example/q> ] ;
>             ns1:predicate rdf:predicate ],
>         [ ns2:objectMap [ ns1:template "http://example/{c5}" ] ;
>             ns1:predicate rdf:object ] .
> ```
> 
> and
> 
> ```
> @prefix ns1: <http://www.w3.org/ns/r2rml#> .
> @prefix ns2: <http://semweb.mmlab.be/ns/rml#> .
> @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
> 
> <http://example.org/secondTM> a ns2:TriplesMap ;
>     ns2:predicateObjectMap [ ns2:objectMap [ ns1:reference rdf:Statement ] ;
>             ns1:predicate ns2:type ] ;
>     ns1:predicateObjectMap [ ns2:objectMap [ ns1:constant <http://example/q> ] ;
>             ns1:predicate rdf:predicate ] ; 
>     ns1:predicateObjectMap [ ns2:objectMap [ ns1:template "http://example/{c5}" ] ;
>             ns1:predicate rdf:object ] .
> ```
> 
> As they both give the same output in https://www.easyrdf.org/converter
> 
> ```
> <http://example.org/secondTM> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://semweb.mmlab.be/ns/rml#TriplesMap> .
> <http://example.org/secondTM> <http://semweb.mmlab.be/ns/rml#predicateObjectMap> _:genid1 .
> <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid3 .
> <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid5 .
> _:genid2 <http://www.w3.org/ns/r2rml#reference> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement> .
> _:genid1 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid2 .
> _:genid1 <http://www.w3.org/ns/r2rml#predicate> <http://semweb.mmlab.be/ns/rml#type> .
> _:genid4 <http://www.w3.org/ns/r2rml#constant> <http://example/q> .
> _:genid3 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid4 .
> _:genid3 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> .
> _:genid6 <http://www.w3.org/ns/r2rml#template> "http://example/{c5}" .
> _:genid5 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid6 .
> _:genid5 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> .
> ```
> 
> and
> 
> ```
> <http://example.org/secondTM> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://semweb.mmlab.be/ns/rml#TriplesMap> .
> <http://example.org/secondTM> <http://semweb.mmlab.be/ns/rml#predicateObjectMap> _:genid1 .
> <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid3 .
> <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid5 .
> _:genid2 <http://www.w3.org/ns/r2rml#reference> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement> .
> _:genid1 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid2 .
> _:genid1 <http://www.w3.org/ns/r2rml#predicate> <http://semweb.mmlab.be/ns/rml#type> .
> _:genid4 <http://www.w3.org/ns/r2rml#constant> <http://example/q> .
> _:genid3 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid4 .
> _:genid3 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> .
> _:genid6 <http://www.w3.org/ns/r2rml#template> "http://example/{c5}" .
> _:genid5 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid6 .
> _:genid5 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> .
> ```
> 
> Therefore I submit that I shouldn't code anything more as the output reification in both cases is equivalent.

If the output is the same, it is ok. But you can use a function to compare your output with the ones created manually  https://github.com/RDFLib/rdflib/blob/master/rdflib/compare.py

**Comment by jhculb** [comment]
> > Can I check whether I am correct in thinking line 50 in rml-star-mappings should be a rr:reference rather than a rml:reference?
> > Otherwise this is inconsistent with the bnode datatype references in rml-star-mappings.
> 
> It is always rml:reference, rr:reference does not exist

Ah ok, I'll sort that out now then :)

**Comment by jhculb** [comment]
> > > Can I check whether I am correct in thinking line 50 in rml-star-mappings should be a rr:reference rather than a rml:reference?
> > > Otherwise this is inconsistent with the bnode datatype references in rml-star-mappings.
> > 
> > 
> > It is always rml:reference, rr:reference does not exist
> 
> Ah ok, I'll sort that out now then :)

Hi @dachafra, I think I've sorted this. I'm just going to sort out the compare function and triple check.

**Comment by jhculb** [comment]
> > > > If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`
> > > 
> > > 
> > > Thanks for the swift reply!
> > > First point: Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.
> > 
> > 
> > You can print the rules in N-Triples to see all without BN
> > > Second point: ns0 is an automatically generated namespace identifier (from RDFlib), e.g. @Prefix ns1: http://www.w3.org/ns/r2rml# .
> > 
> > 
> > I think you can manage them with Namespaces right?
> 
> First point, outputting using rdflib serialize and ntriples does include BNodes (see syntax-2.ttl in /generated-rml-reified)
> 
> Second point, the two namespaces are equivalent, just with a different variable. I haven't seen anything in the documentation that allows me edit these directly, I can see what I can do but I think apart from the naming convention (ns0 for (e.g.) rr, ns1 for (e.g.) rml) the generated reified documents are the same as the manually reified documents. (And apart from the first point)

It looks like RDFlib automatically assigns rdf and xsd namespaces correctly, but hasn't implemented the rml and r2rml automatic namespace assignment, and assigns these to ns1 and ns2. @dachafra

**Comment by jhculb** [comment]
> > > > > > If you are asking if the notation `rr:predicateObjectMap` is needed, it's. Also, I don't know why you have this ` ns0:subject [ rr:parentTriplesMap <http://example.org/firstTM> ] ;`, it should be something like rr:objectMap, and also `ns0:objectMap` should be `rr:objectMap`
> > > > > 
> > > > > 
> > > > > Thanks for the swift reply!
> > > > > First point: Ok, I'll take a look again, but RDFlib seems to be automatically parsing the output in that format even with the correct reference of a new BNode and predicateObjectMap to the TriplesMap. I may be missing something but it feels and looks correct in the code.
> > > > 
> > > > 
> > > > You can print the rules in N-Triples to see all without BN
> > > > > Second point: ns0 is an automatically generated namespace identifier (from RDFlib), e.g. @Prefix ns1: http://www.w3.org/ns/r2rml# .
> > > > 
> > > > 
> > > > I think you can manage them with Namespaces right?
> > > 
> > > 
> > > First point, outputting using rdflib serialize and ntriples does include BNodes (see syntax-2.ttl in /generated-rml-reified)
> > > Second point, the two namespaces are equivalent, just with a different variable. I haven't seen anything in the documentation that allows me edit these directly, I can see what I can do but I think apart from the naming convention (ns0 for (e.g.) rr, ns1 for (e.g.) rml) the generated reified documents are the same as the manually reified documents. (And apart from the first point)
> > 
> > 
> > Hi @dachafra, on the first point: I believe that the following two statements are equivalent:
> > ```
> > @prefix ns1: <http://www.w3.org/ns/r2rml#> .
> > @prefix ns2: <http://semweb.mmlab.be/ns/rml#> .
> > @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
> > 
> > <http://example.org/secondTM> a ns2:TriplesMap ;
> >     ns2:predicateObjectMap [ ns2:objectMap [ ns1:reference rdf:Statement ] ;
> >             ns1:predicate ns2:type ] ;
> >     ns1:predicateObjectMap [ ns2:objectMap [ ns1:constant <http://example/q> ] ;
> >             ns1:predicate rdf:predicate ],
> >         [ ns2:objectMap [ ns1:template "http://example/{c5}" ] ;
> >             ns1:predicate rdf:object ] .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > @prefix ns1: <http://www.w3.org/ns/r2rml#> .
> > @prefix ns2: <http://semweb.mmlab.be/ns/rml#> .
> > @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
> > 
> > <http://example.org/secondTM> a ns2:TriplesMap ;
> >     ns2:predicateObjectMap [ ns2:objectMap [ ns1:reference rdf:Statement ] ;
> >             ns1:predicate ns2:type ] ;
> >     ns1:predicateObjectMap [ ns2:objectMap [ ns1:constant <http://example/q> ] ;
> >             ns1:predicate rdf:predicate ] ; 
> >     ns1:predicateObjectMap [ ns2:objectMap [ ns1:template "http://example/{c5}" ] ;
> >             ns1:predicate rdf:object ] .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As they both give the same output in https://www.easyrdf.org/converter
> > ```
> > <http://example.org/secondTM> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://semweb.mmlab.be/ns/rml#TriplesMap> .
> > <http://example.org/secondTM> <http://semweb.mmlab.be/ns/rml#predicateObjectMap> _:genid1 .
> > <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid3 .
> > <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid5 .
> > _:genid2 <http://www.w3.org/ns/r2rml#reference> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement> .
> > _:genid1 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid2 .
> > _:genid1 <http://www.w3.org/ns/r2rml#predicate> <http://semweb.mmlab.be/ns/rml#type> .
> > _:genid4 <http://www.w3.org/ns/r2rml#constant> <http://example/q> .
> > _:genid3 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid4 .
> > _:genid3 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> .
> > _:genid6 <http://www.w3.org/ns/r2rml#template> "http://example/{c5}" .
> > _:genid5 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid6 .
> > _:genid5 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > <http://example.org/secondTM> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://semweb.mmlab.be/ns/rml#TriplesMap> .
> > <http://example.org/secondTM> <http://semweb.mmlab.be/ns/rml#predicateObjectMap> _:genid1 .
> > <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid3 .
> > <http://example.org/secondTM> <http://www.w3.org/ns/r2rml#predicateObjectMap> _:genid5 .
> > _:genid2 <http://www.w3.org/ns/r2rml#reference> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement> .
> > _:genid1 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid2 .
> > _:genid1 <http://www.w3.org/ns/r2rml#predicate> <http://semweb.mmlab.be/ns/rml#type> .
> > _:genid4 <http://www.w3.org/ns/r2rml#constant> <http://example/q> .
> > _:genid3 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid4 .
> > _:genid3 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> .
> > _:genid6 <http://www.w3.org/ns/r2rml#template> "http://example/{c5}" .
> > _:genid5 <http://semweb.mmlab.be/ns/rml#objectMap> _:genid6 .
> > _:genid5 <http://www.w3.org/ns/r2rml#predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Therefore I submit that I shouldn't code anything more as the output reification in both cases is equivalent.
> 
> If the output is the same, it is ok. But you can use a function to compare your output with the ones created manually https://github.com/RDFLib/rdflib/blob/master/rdflib/compare.py

Hi @dachafra, I've implemented the code to check isomorphic graphs. It looks as if the nodes need to be from the same source in each, as I've implemented the code creating new nodes, it doesn't look like they are isomorphic, though I think they are equivalent (if using different UUIDs for nodes and edges).

**Comment by dachafra** [comment]
OK, I usually have the same problem as well, don't worry

**Review by dachafra — APPROVED** [review]

**Pull request merged**
